version: "3"
networks:
  stream-app:
    driver: bridge
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  bff:
    build:
      context: ./bff
      dockerfile: Local.Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./bff:/app
    command: sh -c "npm install; npm run prebuild; npm run start:debug"
    # env_file:
    #   - docker/.env.backend
    tty: true
  webapp:
    build:
      context: ./webapp
      dockerfile: Local.Dockerfile
    working_dir: /app
    ports:
      - 80:3000
    volumes:
      - ./webapp:/app
    command: npm run dev
