version: "3"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  bff:
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app
    ports:
      - "10020:5443"
    volumes:
      - ./:/app
      - $HOME/.npmrc:/root/.npmrc
    command: sh -c "npm install; npm run prebuild; npm run start:debug"
    env_file:
      - docker/.env.app
      - docker/.env.secrets
    tty: true
  # webapp:
  #   ports:
  #     - 80:80
